version: "3.1"
services:
  db:
    image: postgres:13-alpine
    environment:
      - DB_HOST=db
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - .:/code

  web:
    build: .
    command: python manage.py makemigrations apiusers
    command: python manage.py migrate apiusers
    command: python manage.py migrate --noinput
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  # migration:
  #   image: web
  #   command: python manage.py migrate --noinput
  #   volumes:
  #     - .:/code
  #   depends_on:
  #     - db